version: "3.7"

x-common: &common
  stop_grace_period: 5s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"
    - "nuvlaedge.peripheral.component=True"
    - "nuvlaedge.peripheral.type=usb"

services:
  peripheral-manager-usb:
    <<: *common
    image: nuvlaedge/peripheral-manager-usb:2.2.0
    restart: always
    network_mode: host
    volumes:
      - /dev:/dev:ro
      - /run/udev/control:/run/udev/control:ro
      - nuvlabox-db:/srv/nuvlaedge/shared
    depends_on:
      - agent
