version: "3.7"

x-common: &common
  stop_grace_period: 5s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"
    - "nuvlaedge.peripheral.component=True"
    - "nuvlaedge.peripheral.type=bluetooth"

services:
  peripheral-manager-bluetooth:
    <<: *common
    image: nuvlaedge/peripheral-manager-bluetooth:1.3.0
    restart: on-failure
    network_mode: host
    volumes:
      - nuvlabox-db:/srv/nuvlaedge/shared
    depends_on:
      - agent
