version: "3.7"

x-common: &common
  stop_grace_period: 5s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"

volumes:
  nuvlabox-db:
    driver: local
    labels:
      - "nuvlaedge.volume=True"
      - "nuvlaedge.deployment=production"

services:
  system-manager:
    <<: *common
    image: nuvladev/system-manager:main
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-system-manager
    environment:
      - SKIP_MINIMUM_REQUIREMENTS=${SKIP_MINIMUM_REQUIREMENTS:-False}
      - NUVLAEDGE_DATA_GATEWAY_IMAGE=${NUVLAEDGE_DATA_GATEWAY_IMAGE:-eclipse-mosquitto:2.0.15-openssl}
      - COMPUTE_API_PORT=${COMPUTE_API_PORT:-5000}
      - AGENT_PORT=${AGENT_PORT:-5080}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-nuvlaedge}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nuvlabox-db:/srv/nuvlaedge/shared
    depends_on:
      - on-stop

  agent:
    <<: *common
    image: nuvladev/agent:main
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-agent
    oom_kill_disable: true
    privileged: true
    environment:
      - NUVLAEDGE_API_KEY=${NUVLAEDGE_API_KEY}
      - NUVLAEDGE_API_SECRET=${NUVLAEDGE_API_SECRET}
      - NUVLAEDGE_UUID=${NUVLAEDGE_UUID}
      - NUVLAEDGE_ENGINE_VERSION=latest
      - NUVLAEDGE_IMMUTABLE_SSH_PUB_KEY=${NUVLAEDGE_SSH_PUB_KEY}
      - HOST_HOME=${HOME}
      - VPN_INTERFACE_NAME=${VPN_INTERFACE_NAME:-vpn}
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
      - COMPUTE_API_PORT=${COMPUTE_API_PORT:-5000}
      - AGENT_PORT=${AGENT_PORT:-5080}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-nuvlaedge}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nuvlabox-db:/srv/nuvlaedge/shared
      - /:/rootfs:ro
    ports:
      - "127.0.0.1:${AGENT_PORT:-5080}:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s
    depends_on:
      - compute-api

  compute-api:
    <<: *common
    image: nuvladev/compute-api:main
    restart: on-failure
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-compute-api
    oom_score_adj: -900
    pid: "host"
    environment:
      - HOST=${HOSTNAME:-nuvlaedge}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nuvlabox-db:/srv/nuvlaedge/shared
    ports:
      - "${COMPUTE_API_PORT:-5000}:5000"
    healthcheck:
      test: netstat -tulpn | grep LISTEN | grep 5000 | grep socat
      interval: 20s
      timeout: 10s
      start_period: 30s

  vpn-client:
    <<: *common
    image: nuvladev/vpn-client:main
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-vpn-client
    oom_kill_disable: true
    network_mode: host
    privileged: true
    devices:
      - /dev/net/tun
    environment:
      - NUVLAEDGE_UUID=${NUVLAEDGE_UUID}
    volumes:
      - nuvlabox-db:/srv/nuvlaedge/shared
    depends_on:
      - agent

  job-engine-lite:
    <<: *common
    image: nuvladev/job-lite:master
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-job-engine-lite
    entrypoint: /app/pause.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  on-stop:
    <<: *common
    image: nuvladev/on-stop:main
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-on-stop
    restart: always
    command: pause
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
