version: "3.7"

x-common: &common
  stop_grace_period: 4s
  labels:
    - nuvlabox.component=True
    - nuvlabox.deployment=localhost

x-common-volumes: &common-volumes
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - nuvlabox-db:/srv/nuvlabox/shared

services:
  agent:
    image: nuvlabox/agent:0.2.2
    <<: [ *common, *common-volumes ]
    restart: on-failure
    expose:
      - 5000
    environment:
      - NUVLA_ENDPOINT=local-nuvla-endpoint
      - NUVLA_ENDPOINT_INSECURE=True
    networks:
      localhost:
        aliases:
          - agent
    depends_on:
      - system-manager
      - compute-api

  system-manager:
    image: nuvlabox/system-manager:0.2.3
    <<: [ *common, *common-volumes ]
    restart: always
    ports:
      - 127.0.0.1:3636:3636
    networks:
      localhost:
        aliases:
          - system-manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3636"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s

  compute-api:
    image: nuvlabox/compute-api:0.2.4
    <<: *common
    restart: on-failure
    pid: "host"
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared
    ports:
      - 5000:5000
    environment:
      - HOST=${HOSTNAME}
    depends_on:
      - system-manager


volumes:
  nuvlabox-db:
    driver: local

networks:
  localhost:
    external:
      name: localhost_nuvlabox
