version: "3.6"

x-common: &common
  stop_grace_period: 4s
  labels:
    - nuvlabox.component=True
    - nuvlabox.deployment=production

x-common-volumes: &common-volumes
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - nuvlabox-db:/srv/nuvlabox/shared

services:
  data-gateway:
    image: traefik:2.1.1
    container_name: datagateway
    networks:
      - default
      - nuvlabox-shared-network
    command:
      - --entrypoints.mqtt.address=:1883
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nb-mosquitto:
    image: eclipse-mosquitto:1.6.8
    container_name: nbmosquitto
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mytcprouter.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mytcprouter.entrypoints=mqtt"
      - "traefik.tcp.routers.mytcprouter.service=mosquitto"
      - "traefik.tcp.services.mosquitto.loadbalancer.server.port=1883"

  agent:
    image: nuvlabox/agent:1.3.0
    <<: [ *common ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nuvlabox-db:/srv/nuvlabox/shared
      - /:/rootfs:ro
    restart: on-failure
    expose:
      - 5000
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
    depends_on:
      - system-manager
      - compute-api

  system-manager:
    image: nuvlabox/system-manager:1.0.0
    <<: [ *common, *common-volumes ]
    restart: always
    ports:
      - 127.0.0.1:3636:3636
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3636"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s

  management-api:
    image: nuvlabox/management-api:0.0.1
    <<: [ *common ]
    volumes:
      - /proc/sysrq-trigger:/sysrq
      - ${HOME}/.ssh/authorized_keys:/rootfs/.ssh/authorized_keys
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s
    ports:
      - 5001:5001

  compute-api:
    image: nuvlabox/compute-api:0.2.5
    <<: [ *common, *common-volumes ]
    restart: on-failure
    pid: "host"
    ports:
      - 5000:5000
    environment:
      - HOST=${HOSTNAME:-nuvlabox}
    depends_on:
      - system-manager

  peripheral-manager-usb:
    image: nuvlabox/peripheral-manager-usb:1.0.2
    <<: *common
    restart: on-failure
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
    depends_on:
      - system-manager
    volumes:
      - /dev:/dev:ro
      - /run/udev/control:/run/udev/control:ro
      - nuvlabox-db:/srv/nuvlabox/shared
    network_mode: host

  peripheral-manager-modbus:
    image: nuvlabox/peripheral-manager-modbus:0.0.2
    <<: *common
    restart: on-failure
    environment:
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
    depends_on:
      - system-manager
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared

  network-manager:
    image: nuvlabox/network-manager:0.0.4
    <<: *common
    restart: on-failure
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
      - VPN_INTERFACE_NAME=${NUVLABOX_VPN_IFACE:-vpn}
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production

  vpn-client:
    image: nuvlabox/vpn-client:0.0.3
    container_name: vpn-client
    <<: *common
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
    depends_on:
      - network-manager
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: host
    devices:
      - /dev/net/tun
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production

volumes:
  nuvlabox-db:
    driver: local

networks:
  nuvlabox-shared-network:
    driver: overlay
    name: nuvlabox-shared-network
    attachable: true
