version: "3.6"

x-common: &common
  stop_grace_period: 4s
  labels:
    - nuvlabox.component=True
    - nuvlabox.deployment=localhost

x-common-volumes: &common-volumes
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - nuvlabox-db:/srv/nuvlabox/shared

services:
  agent:
    image: nuvlabox/agent:1.2.0
    <<: [ *common, *common-volumes ]
    restart: on-failure
    expose:
      - 5000
    environment:
      - NUVLA_ENDPOINT=local-nuvla-endpoint
      - NUVLA_ENDPOINT_INSECURE=True
      - NUVLABOX_UUID=${NUVLABOX_UUID}
    networks:
      localhost:
        aliases:
          - agent
    depends_on:
      - system-manager
      - compute-api

  system-manager:
    image: nuvlabox/system-manager:0.4.1
    <<: [ *common, *common-volumes ]
    restart: always
    ports:
      - 127.0.0.1:3636:3636
      - 3637:3637
    networks:
      localhost:
        aliases:
          - system-manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3636"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s

  compute-api:
    image: nuvlabox/compute-api:0.2.5
    <<: [ *common, *common-volumes ]
    restart: on-failure
    pid: "host"
    ports:
      - 5000:5000
    environment:
      - HOST=${HOSTNAME}
    depends_on:
      - system-manager

  peripheral-manager-usb:
    image: nuvlabox/peripheral-manager-usb:1.0.2
    <<: *common
    restart: on-failure
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
      - NUVLA_ENDPOINT=localhost
      - NUVLA_ENDPOINT_INSECURE=True
    depends_on:
      - system-manager
    volumes:
      - /dev:/dev:ro
      - /run/udev/control:/run/udev/control:ro
      - nuvlabox-db:/srv/nuvlabox/shared
    network_mode: host

  peripheral-manager-modbus:
    image: nuvlabox/peripheral-manager-modbus:0.0.1
    <<: *common
    restart: on-failure
    environment:
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
    depends_on:
      - system-manager
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared

  network-manager:
    image: nuvlabox/network-manager:0.0.2
    <<: *common
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production

  vpn-client:
    image: nuvlabox/vpn-client:0.0.3
    container_name: vpn-client
    <<: *common
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
    depends_on:
      - network-manager
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: host
    devices:
      - /dev/net/tun
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production

volumes:
  nuvlabox-db:
    driver: local

networks:
  localhost:
    external:
      name: localhost_nuvlabox
