version: "3.7"

x-common: &common
  stop_grace_period: 5s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"

volumes:
  nuvlabox-db:
    driver: local
    labels:
      - "nuvlaedge.volume=True"
      - "nuvlaedge.deployment=production"

services:
  system-manager:
    <<: *common
    image: nuvlaedge/system-manager:2.5.0
    restart: always
    environment:
      - SKIP_MINIMUM_REQUIREMENTS=${SKIP_MINIMUM_REQUIREMENTS:-False}
      - NUVLAEDGE_DATA_GATEWAY_IMAGE=${NUVLAEDGE_DATA_GATEWAY_IMAGE:-eclipse-mosquitto:1.6.12}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nuvlabox-db:/srv/nuvlaedge/shared
    ports:
      - 127.0.0.1:3636:3636
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3636"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s
    depends_on:
      - on-stop

  agent:
    <<: *common
    image: nuvlaedge/agent:2.9.1
    restart: always
    oom_kill_disable: true
    privileged: true
    environment:
      - NUVLAEDGE_API_KEY=${NUVLAEDGE_API_KEY}
      - NUVLAEDGE_API_SECRET=${NUVLAEDGE_API_SECRET}
      - NUVLAEDGE_UUID=${NUVLAEDGE_UUID}
      - NUVLAEDGE_ENGINE_VERSION=2.5.0
      - NUVLAEDGE_IMMUTABLE_SSH_PUB_KEY=${NUVLAEDGE_SSH_PUB_KEY}
      - HOST_HOME=${HOME}
      - VPN_INTERFACE_NAME=${VPN_INTERFACE_NAME:-vpn}
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nuvlabox-db:/srv/nuvlaedge/shared
      - /:/rootfs:ro
    ports:
      - 127.0.0.1:5080:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s
    depends_on:
      - compute-api

  compute-api:
    <<: *common
    image: nuvlaedge/compute-api:1.3.0
    container_name: compute-api
    restart: on-failure
    oom_score_adj: -900
    pid: "host"
    environment:
      - HOST=${HOSTNAME:-nuvlaedge}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nuvlabox-db:/srv/nuvlaedge/shared
    ports:
      - 5000:5000
    healthcheck:
      test: netstat -tulpn | grep LISTEN | grep 5000 | grep socat
      interval: 20s
      timeout: 10s
      start_period: 30s

  vpn-client:
    <<: *common
    image: nuvlaedge/vpn-client:1.2.0
    container_name: vpn-client
    restart: always
    oom_kill_disable: true
    network_mode: host
    privileged: true
    devices:
      - /dev/net/tun
    environment:
      - NUVLAEDGE_UUID=${NUVLAEDGE_UUID}
    volumes:
      - nuvlabox-db:/srv/nuvlaedge/shared
    depends_on:
      - agent

  job-engine-lite:
    <<: *common
    image: nuvla/job-lite:3.1.0
    restart: always
    container_name: nuvlaedge-job-engine-lite
    entrypoint: /app/pause.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  on-stop:
    <<: *common
    image: nuvlaedge/on-stop:1.2.0
    restart: always
    container_name: nuvlaedge-on-stop
    command: pause
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
