version: "3.7"

x-common: &common
  stop_grace_period: 5s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"
    - "nuvlaedge.peripheral.component=True"
    - "nuvlaedge.peripheral.type=modbus"

services:
  peripheral-manager-modbus:
    <<: *common
    image: nuvlaedge/peripheral-manager-modbus:1.4.0
    restart: on-failure
    depends_on:
      - agent
