version: "3.6"

x-common: &common
  stop_grace_period: 4s
  labels:
    - nuvlabox.component=True
    - nuvlabox.deployment=production

x-common-volumes: &common-volumes
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - nuvlabox-db:/srv/nuvlabox/shared

services:
  agent:
    image: nuvlabox/agent:1.0.0
    <<: [ *common, *common-volumes ]
    restart: on-failure
    expose:
      - 5000
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
    depends_on:
      - system-manager
      - compute-api

  system-manager:
    image: nuvlabox/system-manager:0.3.1
    <<: [ *common, *common-volumes ]
    restart: always
    ports:
      - 127.0.0.1:3636:3636
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3636"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s

  compute-api:
    image: nuvlabox/compute-api:0.2.4
    <<: [ *common, *common-volumes ]
    restart: on-failure
    pid: "host"
    ports:
      - 5000:5000
    environment:
      - HOST=${HOSTNAME}
    depends_on:
      - system-manager

#  peripheral-manager-usb:
#    image: nuvlabox/peripheral-manager-usb:1.0.0
#    <<: *common
#    restart: on-failure
#    environment:
#      - NUVLABOX_UUID=${NUVLABOX_UUID}
#    depends_on:
#      - system-manager
#    volumes:
#      - /dev:/dev:ro
#      - /run/udev/control:/run/udev/control:ro
#      - nuvlabox-db:/srv/nuvlabox/shared
#    network_mode: host

volumes:
  nuvlabox-db:
    driver: local
