apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-credentials-manager-deployment
  namespace: {{ include "nuvlaedge-engine.namespace" . }}
  labels:
    {{- include "nuvlaedge-engine.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      component: kubernetes-credentials-manager
  template:
    metadata:
      labels:
        component: kubernetes-credentials-manager
        {{- include "nuvlaedge-engine.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.kubernetesNode }}
      containers:
        - name: kubernetes-credentials-manager
          image: "{{ .Values.images.kubernetesCredentialsManager.repository }}:{{ .Values.images.kubernetesCredentialsManager.tag }}"
          imagePullPolicy: {{ .Values.images.kubernetesCredentialsManager.pullPolicy }}
          volumeMounts:
            - mountPath: /srv/nuvlaedge/shared
              name: nuvlaedge-db
          env:
            - name: WAIT_APPROVED_SEC
              value: "{{ .Values.credManager.wait_approved_sec }}"
            - name: CSR_NAME
              value: {{ .Values.credManager.csr_name }}

      ## VOLUMES
      volumes:
        - name: nuvlaedge-db
          hostPath:
            path: /var/lib/{{ include "nuvlaedge-engine.namespace" . }}
