{{- if .Values.peripheralManagerBluetooth }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peripheral-manager-bluetooth-deployment
  namespace: {{ include "nuvlaedge-engine.namespace" . }}
  labels:
    {{- include "nuvlaedge-engine.labels" . | nindent 4 }}
    {{- include "nuvlaedge-engine.peripheral-manager.labels" . | nindent 4 }}
    nuvlaedge.peripheral.type: bluetooth
spec:
  selector:
    matchLabels:
      component: peripheral-manager-bluetooth
  template:
    metadata:
      labels:
        component: peripheral-manager-bluetooth
        {{- include "nuvlaedge-engine.labels" . | nindent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.kubernetesNode }}
      containers:
        - name: peripheral-manager-bluetooth
          image: "{{ .Values.images.peripheralManagerBluetooth.repository }}:{{ .Values.images.peripheralManagerBluetooth.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.peripheralManagerBluetooth.pullPolicy }}
          env:
            - name: MY_NAMESPACE
              value: {{ include "nuvlaedge-engine.namespace" . }}
{{- end }}
