# Automatic release of NuvlaBox Engine, for every new tag
name: "tagged-release"

on:
  push:
    tags:
      - "*.*.*"

jobs:
  tagged-release:
    name: "Tagged NuvlaBox Engine Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: v${{ github.event.release.tag_name }}
          files: |
            install.sh
            *.yml
