# Automatic release of NuvlaBox Engine, for every new tag
name: "tagged-release"

on:
  push:
    tags:
      - "*.*.*"

jobs:
  tagged-release:
    name: "Tagged NuvlaBox Engine Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            install.sh
            *.yml

  notify:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - tagged-release
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          icon_emoji: ':rocket:'