name: "NuvlaEdge Device and System validation tests"

on:
  push:
    branches:
      - "validation-tests"
    pull_request:
  workflow_dispatch:


jobs:
  validate-release:
    runs-on: validation-runner
    strategy:
      matrix:
        board-config: [ "1_rpi4.toml", "2_ubuntu_vm.toml" ]
        validation-type: [ "basic_tests", "nuvla_operations" ]

    steps:
      - name: CheckOut validation packages
        run: |
          "curl -H 'Authorization: ${{ secrets.VALIDATION_TOKEN_USERNAME }} ${{secrets.VALIDATION_TOKEN_SECRET}}' -H 'Accept: application/vnd.github.v3.raw' \
          -O -L https://api.github.com/repos/nuvlaedge/validation/contentes/dist/"

      - name: Gather System configuration
        run: |
          "curl -H 'Authorization: ${{ secrets.VALIDATION_TOKEN_USERNAME }} ${{secrets.VALIDATION_TOKEN_SECRET}}' -H 'Accept: application/vnd.github.v3.raw' \
          -O -L https://api.github.com/repos/nuvlaedge/validation/contents/conf/"

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Validation Framework dependency
        working-directory: ./dist/
        run: pip install validation-0.0.1a1-py3-none-any.whl  --force-reinstall

      - name: Run Validation on board ${{ matrix.board-config }}
        working-directory: ./validation_framework
        run: python -m validation_framework --target ${{ matrix.board-config }} --validator ${{ matrix.validation-type }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: "temp_results/xml/*.xml"
